/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * Copyright 2023-2026 The Konstraints Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package tools.aqua.konstraints.solvers

import tools.aqua.konstraints.parser.SMTScriptParser
import tools.aqua.konstraints.smt.Model
import tools.aqua.konstraints.smt.SMTProgram
import tools.aqua.konstraints.smt.SatStatus

class EarliestSolver(
    override val solvers: List<Solver>,
    val condition: ((Solver, SatStatus) -> Boolean)?,
) : MetaSolver {
  override fun solve(program: SMTProgram, policy: ExecutionPolicy): SatStatus {
    return if (condition != null) {
      when (policy) {
        ExecutionPolicy.SEQUENTIAL ->
            solveSequential(
                program,
                condition,
                List<SatStatus>::isNotEmpty,
                List<SatStatus>::single,
                SatStatus.PENDING,
                300000,
            )

        // pass earliest condition as validate result, then early abort when at least one result is
        // ready, reducing the results list to its only member
        ExecutionPolicy.PARALLEL ->
            solveParallel(
                program,
                condition,
                List<SatStatus>::isNotEmpty,
                List<SatStatus>::single,
                SatStatus.PENDING,
                300000,
            )
      }
    } else {
      // without a condition this acts as a meta solver for the earliest pattern instead of
      // earliest trusted
      when (policy) {
        ExecutionPolicy.SEQUENTIAL ->
            solveParallel(
                program,
                { solver, status -> true },
                List<SatStatus>::isNotEmpty,
                List<SatStatus>::single,
                SatStatus.PENDING,
                300000,
            )
        ExecutionPolicy.PARALLEL ->
            solveParallel(
                program,
                { solver, status -> true },
                List<SatStatus>::isNotEmpty,
                List<SatStatus>::single,
                SatStatus.PENDING,
                300000,
            )
      }
    }
  }

  override fun solve(program: SMTProgram) = solve(program, ExecutionPolicy.PARALLEL)

  override fun getModel(): Model {
    TODO("Not yet implemented")
  }

  override fun close() {
    solvers.forEach { it.close() }
  }
}

fun main() {
  val program =
      SMTScriptParser(
          "(set-info :smt-lib-version 2.6)\n" +
              "(set-logic QF_S)\n" +
              "(set-info :source |\n" +
              "Generated by: Shaoke Cui\n" +
              "Generated on: 2025-04-10\n" +
              "Application: Using String Solvers to solve string matching problems\n" +
              "Target solver: cvc5, OSTRICH, Z3, Z3alpha, Z3-noodler\n" +
              "Benchmarks for substring matching problem, which needs to determine whether the pattern string exists in the text string.\n" +
              "|)\n" +
              "(set-info :license \"https://creativecommons.org/licenses/by/4.0/\")\n" +
              "(set-info :category \"crafted\")\n" +
              "(set-info :status sat)\n" +
              "(declare-fun a() String)\n" +
              "(declare-fun b() String)\n" +
              "(assert (= a \"ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp\"))\n" +
              "(assert (= b \"pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp\"))\n" +
              "(assert (str.contains (str.++ b b b a a b a a b a b b a b a b b b b b a b a a a b a b b a b b b b b a a b b b b a b b b a b b a a a b a b a b b b b b a a a a a a a b b b b a a a b a a a b b a a b b a a b b a b a a a b a b b a a b b a a b b a a a b b a a a b a b b b a b a b a b a a b b a b a b a a a a b b b a b a a a b a b a a a b a b b b b b a b a b b b b a b b a a a a b a b b b a b a a b a a a b a b b a a a a a b b b b b b a b b b b b b b b b a a a b a b a a a b a a b a a b a b a b b b b a b a b a b b b b b a a b b b a a b b a a b b a a b b b b b a b b a a b a b a a a b a b b b b a a b b b b a a a b a a b a a b b b a b b a a b b a b a a b b a b a a a b a a a a b a b a a a a a b b a b b b a a a a a b a a b a a b a a a b a a b a a b a b b b b a b b b a b b a a a b a a a b b b b b b b b b a a b a a a b b a b b a a b b b a b a b a b b b a b a b a b a a a b a a b b a b b b a b a a b b b b a b b b b b b b b a b a a b a b a a a a b a b a a a a b a a a a b b a a b b a b a a a b b b b a b a b a a b b a a a b b b a a b b a b b b b a a a a a a b a a b b a b a b a b a b b b b a b a a b a a b a a b b b a a b a b a b a b a b a a b b b b a b b b b a b a a b b b b a b a a a a b b b a b b a b a a a a b b a a a a a b b a a a b a a a b b b b b b b a a a a a a b a a b b b a b b a b a a a b b a b a a a a a b b b a a b a a a b b a a a a b b b b b a a b b a a a b a a b b a b b a a a a a b a b b b b b b b b a b a a a b b a b b b b b b b a a a a b b b a b a a a a a b b b a a a a a b a b a a a a a b a b b a b b a b b a b a a a b a b b a a b a b a b b a a b a a a a a a b a b b b b b b b b b a b a a b b a a b a b a a b b a a a b a a b a b b b a a b b b a b b a a b a a b b a b b a b a b b b b a b b a b a b a b a b b a a a b b b a a a a a a b a b a a b b b b a b a b b a b b a a a a b a b b a b b b a b b b b a a a b a b a a b a b b b b a a a a a a a a b b a b a a b a a a a b b b b b a a b b b b b b a b a b b a a a a a a b b b a b a b b b b b b b b b b b a a b b b a a a a b b b a a a a a a a b b b b b b a b b a b a a a a b b a a b b a a b b b b b b b b a a b b b b a b b a b b b a a a a a b b b a a a a a b b a a b b a a a a a b a a a a b a b a b b b a b a a a a b b a b b a b a a b a b a b b b b b a b a b a b b a b a a a b a a b a b a b a b a a a a b a b a a a b b b a b a b b a b b a a b a a b a a a a b b b b b b a a a a a b a a b b b a a b b b a b a a b b b a b a b b b a a b b b b b a b a a b a a a b a b a a a a a a b b b b b b b b a a b b b a a a b b a b a a a b a b b b a b a a a a a a b a a b a a a a b b b a b a a a a a a b b a b b a b b b b a a a b a a b b b b b b b b a b b a b a a b b b b b b b a b a b b b b a a a a b b b a b a a b b a b a b a a b a a a b b a a a b b a a b a a b a b b a a b a a a b b b a b a a a b a b a b b b a a a b a a b a b b a b b b b a b b b b b a a a a a b b a b b b b b b a a a b b b b b b a b b a a b b a b b b b a a b a a a b b b b b b b b a b a b b a  \"1\" a a a a a a a a a a ) (str.++ a a a b a b a b a a a a a a a a b b a a a a a b a b b b a b a b a b b b a b a b b a b a a a a a a b a a b b a b b a b a b a a a b a b b b b b a a a a a b b a b a a a a b b a a a a a a b a a b a a b b b a a a b b a b b a a a a a a a a b b a a a a b b a b b a b a b b b b a b a a a b a a a a a a a b b a a a b a b a a a a b a a b a b a a a b a a a b a a b b b b b b b b b b a b a a b b a a a a a a a a a b b b a b a b b a b a a a a a b a a b b b a a a a a a b b b b a  \"1\")))\n" +
              "(check-sat)\n" +
              "(exit)\n"
      )

  EarliestSolver(listOf(InteractiveCVC5Solver())) { solver, status -> true }
}
